import {
  boolean,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  real,
  text,
  timestamp,
  uniqueIndex,
  vector,
} from "drizzle-orm/pg-core";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  version: integer("version").default(1).notNull(),
};
const editable = { ...timestamps, deleted: boolean("deleted").default(false).notNull() };

export const taskStatus = pgEnum("task_status", ["backlog", "planned", "in_progress", "blocked", "done"]);
export const evidenceStatus = pgEnum("evidence_status", ["direct_support", "indirect_support", "model_inference", "user_hypothesis", "contradicted", "unverified"]);

export const users = pgTable("users", { id: text("id").primaryKey(), email: text("email").notNull(), ...editable }, (table) => [uniqueIndex("users_email_idx").on(table.email)]);
export const profiles = pgTable("profiles", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), displayName: text("display_name").notNull(), timezone: text("timezone").notNull(), educationLevel: text("education_level"), preferences: jsonb("preferences").$type<Record<string, unknown>>().default({}).notNull(), ...editable });
export const integrations = pgTable("integrations", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), provider: text("provider").notNull(), encryptedCredentials: text("encrypted_credentials"), scopes: text("scopes").array().default([]).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }), ...editable });
export const goals = pgTable("goals", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), title: text("title").notNull(), outcome: text("outcome").notNull(), targetDate: timestamp("target_date", { withTimezone: true }).notNull(), status: text("status").default("active").notNull(), progress: real("progress").default(0).notNull(), uncertainFields: text("uncertain_fields").array().default([]).notNull(), ...editable });
export const milestones = pgTable("milestones", { id: text("id").primaryKey(), goalId: text("goal_id").references(() => goals.id).notNull(), title: text("title").notNull(), status: text("status").default("upcoming").notNull(), dueAt: timestamp("due_at", { withTimezone: true }), order: integer("order").notNull(), ...editable });
export const tasks = pgTable("tasks", { id: text("id").primaryKey(), goalId: text("goal_id").references(() => goals.id).notNull(), title: text("title").notNull(), description: text("description"), status: taskStatus("status").default("backlog").notNull(), estimatedMinutes: integer("estimated_minutes").notNull(), deadline: timestamp("deadline", { withTimezone: true }), priority: integer("priority").notNull(), energyRequired: text("energy_required").notNull(), completionEvidence: text("completion_evidence"), generatedBy: text("generated_by"), promptVersion: text("prompt_version"), ...editable });
export const taskDependencies = pgTable("task_dependencies", { id: text("id").primaryKey(), taskId: text("task_id").references(() => tasks.id).notNull(), dependsOnTaskId: text("depends_on_task_id").references(() => tasks.id).notNull(), ...editable });
export const calendarConstraints = pgTable("calendar_constraints", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), title: text("title").notNull(), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), hard: boolean("hard").default(true).notNull(), ...editable });
export const scheduleBlocks = pgTable("schedule_blocks", { id: text("id").primaryKey(), taskId: text("task_id").references(() => tasks.id).notNull(), startsAt: timestamp("starts_at", { withTimezone: true }).notNull(), endsAt: timestamp("ends_at", { withTimezone: true }).notNull(), status: text("status").default("planned").notNull(), proposalId: text("proposal_id").notNull(), committedAt: timestamp("committed_at", { withTimezone: true }), ...editable });
export const curricula = pgTable("curricula", { id: text("id").primaryKey(), authority: text("authority").notNull(), title: text("title").notNull(), sourceVersion: text("source_version").notNull(), humanReviewed: boolean("human_reviewed").default(false).notNull(), ...editable });
export const curriculumNodes = pgTable("curriculum_nodes", { id: text("id").primaryKey(), curriculumId: text("curriculum_id").references(() => curricula.id).notNull(), topic: text("topic").notNull(), outcomes: text("outcomes").array().default([]).notNull(), prerequisiteIds: text("prerequisite_ids").array().default([]).notNull(), sourceIds: text("source_ids").array().default([]).notNull(), ...editable });
export const concepts = pgTable("concepts", { id: text("id").primaryKey(), curriculumNodeId: text("curriculum_node_id").references(() => curriculumNodes.id), title: text("title").notNull(), description: text("description").notNull(), prerequisiteIds: text("prerequisite_ids").array().default([]).notNull(), ...editable });
export const learningStates = pgTable("learning_states", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), conceptId: text("concept_id").references(() => concepts.id).notNull(), exposure: real("exposure").default(0).notNull(), understanding: real("understanding").default(0).notNull(), transfer: real("transfer").default(0).notNull(), retention: real("retention").default(0).notNull(), status: text("status").notNull(), evidenceIds: text("evidence_ids").array().default([]).notNull(), explanation: text("explanation").notNull(), ...editable });
export const assessments = pgTable("assessments", { id: text("id").primaryKey(), conceptId: text("concept_id").references(() => concepts.id).notNull(), kind: text("kind").notNull(), items: jsonb("items").$type<unknown[]>().notNull(), model: text("model"), promptVersion: text("prompt_version"), ...editable });
export const assessmentAttempts = pgTable("assessment_attempts", { id: text("id").primaryKey(), assessmentId: text("assessment_id").references(() => assessments.id).notNull(), userId: text("user_id").references(() => users.id).notNull(), answers: jsonb("answers").$type<unknown[]>().notNull(), score: real("score").notNull(), unseen: boolean("unseen").default(false).notNull(), ...timestamps });
export const misconceptions = pgTable("misconceptions", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), conceptId: text("concept_id").references(() => concepts.id).notNull(), attemptId: text("attempt_id").references(() => assessmentAttempts.id).notNull(), label: text("label").notNull(), status: text("status").notNull(), confidence: real("confidence").notNull(), ...editable });
export const projects = pgTable("projects", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), goalId: text("goal_id").references(() => goals.id), title: text("title").notNull(), purpose: text("purpose").notNull(), phase: text("phase").notNull(), ...editable });
export const projectDecisions = pgTable("project_decisions", { id: text("id").primaryKey(), projectId: text("project_id").references(() => projects.id).notNull(), text: text("text").notNull(), reasoning: text("reasoning").notNull(), status: text("status").notNull(), sourceIds: text("source_ids").array().default([]).notNull(), supersedesId: text("supersedes_id"), ...editable });
export const sources = pgTable("sources", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), projectId: text("project_id").references(() => projects.id), title: text("title").notNull(), mimeType: text("mime_type").notNull(), storagePath: text("storage_path"), contentHash: text("content_hash").notNull(), sourceVersion: integer("source_version").default(1).notNull(), parserVersion: text("parser_version").notNull(), ...editable }, (table) => [index("sources_hash_idx").on(table.contentHash)]);
export const sourceChunks = pgTable("source_chunks", { id: text("id").primaryKey(), sourceId: text("source_id").references(() => sources.id).notNull(), passage: integer("passage").notNull(), content: text("content").notNull(), contentHash: text("content_hash").notNull(), embedding: vector("embedding", { dimensions: 1536 }), ...editable }, (table) => [index("source_chunks_source_idx").on(table.sourceId)]);
export const papers = pgTable("papers", { id: text("id").primaryKey(), projectId: text("project_id").references(() => projects.id).notNull(), sourceId: text("source_id").references(() => sources.id), title: text("title").notNull(), authors: text("authors").array().default([]).notNull(), doi: text("doi"), year: integer("year"), ...editable });
export const researchNotes = pgTable("research_notes", { id: text("id").primaryKey(), projectId: text("project_id").references(() => projects.id).notNull(), sourceId: text("source_id").references(() => sources.id), chunkId: text("chunk_id").references(() => sourceChunks.id), text: text("text").notNull(), createdBy: text("created_by").notNull(), ...editable });
export const researchClaims = pgTable("research_claims", { id: text("id").primaryKey(), projectId: text("project_id").references(() => projects.id).notNull(), text: text("text").notNull(), status: text("status").notNull(), createdBy: text("created_by").notNull(), verificationModel: text("verification_model"), supersedesId: text("supersedes_id"), ...editable });
export const claimEvidence = pgTable("claim_evidence", { id: text("id").primaryKey(), claimId: text("claim_id").references(() => researchClaims.id).notNull(), sourceId: text("source_id").references(() => sources.id).notNull(), chunkId: text("chunk_id").references(() => sourceChunks.id).notNull(), status: evidenceStatus("status").notNull(), verifierRouteId: text("verifier_route_id"), ...editable });
export const artifacts = pgTable("artifacts", { id: text("id").primaryKey(), projectId: text("project_id").references(() => projects.id).notNull(), title: text("title").notNull(), kind: text("kind").notNull(), storagePath: text("storage_path"), metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(), ...editable });
export const memoryEvents = pgTable("memory_events", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), type: text("type").notNull(), goalId: text("goal_id").references(() => goals.id), entityId: text("entity_id"), payload: jsonb("payload").$type<Record<string, unknown>>().notNull(), source: jsonb("source").$type<Record<string, unknown>>().notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() }, (table) => [index("memory_events_user_time_idx").on(table.userId, table.occurredAt)]);
export const memoryRecords = pgTable("memory_records", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), type: text("type").notNull(), entityId: text("entity_id"), value: jsonb("value").$type<Record<string, unknown>>().notNull(), sourceEventId: text("source_event_id").references(() => memoryEvents.id).notNull(), superseded: boolean("superseded").default(false).notNull(), ...editable });
export const modelRoutes = pgTable("model_routes", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), taskClass: text("task_class").notNull(), provider: text("provider").notNull(), model: text("model").notNull(), reason: text("reason").notNull(), verificationStatus: text("verification_status").notNull(), fallbackUsed: boolean("fallback_used").default(false).notNull(), ...timestamps });
export const modelUsage = pgTable("model_usage", { id: text("id").primaryKey(), routeId: text("route_id").references(() => modelRoutes.id).notNull(), userId: text("user_id").references(() => users.id).notNull(), inputTokens: integer("input_tokens").notNull(), outputTokens: integer("output_tokens").notNull(), costClass: text("cost_class").notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const auditLog = pgTable("audit_log", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id).notNull(), actor: text("actor").notNull(), action: text("action").notNull(), entityIds: text("entity_ids").array().default([]).notNull(), changeSummary: text("change_summary").notNull(), metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}).notNull(), occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull(), createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull() });
export const oauthClients = pgTable("oauth_clients", { id: text("id").primaryKey(), name: text("name").notNull(), redirectUris: text("redirect_uris").array().notNull(), scopes: text("scopes").array().notNull(), publicClient: boolean("public_client").default(true).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }), ...timestamps });
export const oauthTokens = pgTable("oauth_tokens", { id: text("id").primaryKey(), clientId: text("client_id").references(() => oauthClients.id).notNull(), userId: text("user_id").references(() => users.id).notNull(), tokenHash: text("token_hash").notNull(), refreshTokenHash: text("refresh_token_hash"), scopes: text("scopes").array().notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }), ...timestamps }, (table) => [uniqueIndex("oauth_tokens_hash_idx").on(table.tokenHash)]);
